apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
     app: hello-pod
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
      app: hello-pod
